---
repos:
- repo: https://github.com/ansible/ansible-lint.git
  rev: v6.2.1
  hooks:
    - id: ansible-lint

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
    - id: codespell
