---
- name: Install extended services
  hosts: all
  become: true
  tasks:
    - name: Install Postfix
      ansible.builtin.package:
        name: postfix
        state: latest
      when: inventory_hostname in groups["web"]
    - name: Install database in corresponding group
      ansible.builtin.package:
        name: postgresql
        state: latest
      when: inventory_hostname in groups["database"]
