version: "3"
virtualmachines:
- name: jhb-exec
  image: red-hat-mbu/jhb-exec-image
  shell: /bin/su - rhel -s /bin/bash
  machine_type: n2-standard-2
- name: dublin-hop
  image: red-hat-mbu/dublin-hop-image
  shell: /bin/su - rhel -s /bin/bash
  machine_type: n2-standard-2
- name: raleigh-controller
  image: red-hat-mbu/raleigh-controller-image
  shell: /bin/su - rhel -s /bin/bash
  machine_type: n2-standard-2
