---
- name: Fill motd file with host data
  hosts: node1
  become: true
  tasks:
    - name: Motd Template
      ansible.builtin.template:
        src: motd-facts.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
