name: instruqt-track-test
on:
  # Run CI against all pushes (direct commits, also merged PRs), Pull Requests
  # push:
  # pull_request:
  # Run CI once per day (at 06:00 UTC)
  # This ensures that even if there haven't been commits that we are still
  # testing. This is particularly important to validate the scenarios against
  # changes in ansible-core or ansible-test
  # schedule:
  #   - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  instruqt-track-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: get production tracks
        run: |
          curl 'https://play.instruqt.com/graphql' \
          -H 'Accept-Encoding: gzip, deflate, br' \
          -H 'Content-Type: application/json' \
          -H 'Accept: application/json' \
          -H 'Connection: keep-alive' \
          -H 'Authorization: Bearer ${{ INSTRUQT_TOKEN }}' \
          --data-binary '{"query":"query tracks {\n  tracks(organizationSlug: \"redhat\") {\n    slug\n    maintenance\n  }\n}\n","variables":{}}' --compressed | jq '.data.tracks[] | select(.maintenance==false) | .slug'
        env:
          INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_API_KEY }}
